# This file was generated by GoReleaser. DO NOT EDIT.
cask "rxds" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "75fb01aa311fe6e083059deca690ca2ff0ffd7b69cd12295129b29a0a36974c2"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_macOS_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f2ee2c1d91442727e6d4d121505e17246f8cb86eda3c72c1c82f9fb783a62ce"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "683ab9cfafbb19f623bb1c3cd4a6fd344f1b14b15cbd6c2da5f1c2120963f842"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3aa6a8f0f710682818858b0ef29dec9a69507c919e1e1080b416326e5c07c957"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rxds"
  desc "rx/dialstreamer — streaming TLS certificate harvester"
  homepage "https://github.com/x-stp/rxds"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rxds"

  # No zap stanza required

end
