# This file was generated by GoReleaser. DO NOT EDIT.
cask "rxds" do
  version "1.0.2"

  on_macos do
    on_intel do
      sha256 "814c1018a0d0635c3bd2a11510764fe487f1bc54ae5b7b983998a2f73ced02a5"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_macOS_amd64.tar.gz"
    end
    on_arm do
      sha256 "beaf6b402a44cc29fcff290cc68fe90731135cb0ae1723e7305552092b8b9a5a"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "35a0a334c3f20b2616af63d4528ea36dd383dda2216c1103951853df81389b29"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f00ac9276cc8cdbff405e535bbe3975326304282d4b4df803f7ac9c432fa2ab"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rxds"
  desc "rx/dialstreamer — streaming TLS certificate harvester"
  homepage "https://github.com/x-stp/rxds"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rxds"

  # No zap stanza required

end
