# This file was generated by GoReleaser. DO NOT EDIT.
cask "rxds" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "e92615c52b5dc1428d3f91b9c82f8e66bb369f48a0f9f2c89a2fd1a001a8fcf2"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_macOS_amd64.tar.gz"
    end
    on_arm do
      sha256 "fd3e17efb7cd9b477a25dbe591f8857867661026cc3abecdfc8d85194eebb79a"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_macOS_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "082b6d4c6af0a89b340cdb6f8c21ab3b5e2e1480f66441aa80f43b61c4f0af9b"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "300d6ae526d7f5c479e35ee69c2336d5d1988a8b89920cd38f00c751575934e7"
      url "https://github.com/x-stp/rxds/releases/download/v#{version}/rxds_#{version}_linux_arm64.tar.gz"
    end
  end

  name "rxds"
  desc "rx/dialstreamer — streaming TLS certificate harvester"
  homepage "https://github.com/x-stp/rxds"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "rxds"

  # No zap stanza required

end
